version: '2'

services:
 nexus:
  build: ./nexus
  container_name: nexus
  ports:
    - "8181:8081"
  networks:
      - monitor-net
  logging:
      driver: "fluentd"
  links:
    - fluentd                   

 jenkins:
  build: ./jenkins
  container_name: jenkins
  ports:
    - "8888:8080"
  links:
    - nexus
    - sonar
    - sonardb
    - fluentd
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker
    - /opt/jenkins:/var/lib/jenkins
  depends_on:
    - nexus
    - sonar
    - sonardb
  environment:
    - NEXUS_PORT=8081
    - SONAR_PORT=9000
    - SONAR_DB_PORT=5432
  networks:
      - monitor-net
  logging:
      driver: "fluentd"                

 sonar:
  build: ./sonar
  container_name: sonar
  ports:
   - "9000:9000"
   - "5432:5432"
  links:    
    - sonardb
    - fluentd
  depends_on:    
    - sonardb  
  environment:
   - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar
   - SONARQUBE_JDBC_USERNAME=sonar
   - SONARQUBE_JDBC_PASSWORD=sonar
  networks:
      - monitor-net
  logging:
      driver: "fluentd"             

 sonardb:
  image: postgres
  container_name: sonardb
  environment:
   - POSTGRES_USER=sonar
   - POSTGRES_PASSWORD=sonar
  volumes:
    - /opt/postgres/data:/var/lib/postgresql/data
  networks:
      - monitor-net
  logging:
      driver: "fluentd"
  links:
    - fluentd               

networks:
  monitor-net:
    driver: bridge      
