version: '2'

services:
 seleniumhub:
  image: selenium/hub
  container_name: seleniumhub
  ports:
    - "4444:4444"
  networks:
      - monitor-net
  logging:
      driver: "fluentd"
  links:
    - fluentd                

 firefox:
  image: selenium/node-firefox
  container_name: firefox
  depends_on:
    - seleniumhub
  ports:
    - 5900
  links:
    - seleniumhub
    - fluentd
  environment:
    - HUB_PORT_4444_TCP_ADDR=seleniumhub
    - HUB_PORT_4444_TCP_PORT=4444
  networks:
      - monitor-net
  logging:
      driver: "fluentd"          
    
 chrome:
  image: selenium/node-chrome
  container_name: chrome
  depends_on:
    - seleniumhub
  ports:
    - 5900
  links:
    - seleniumhub
    - fluentd
  environment:
    - HUB_PORT_4444_TCP_ADDR=seleniumhub
    - HUB_PORT_4444_TCP_PORT=4444
  networks:
      - monitor-net
  logging:
      driver: "fluentd"        

networks:
  monitor-net:
    driver: bridge      