version: "2"

services:

  fluentd:
    build: ./fluentd
    container_name: fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ./fluentd/etc:/fluentd/etc
    depends_on: 
      - elasticsearch  
    links:
      - elasticsearch
    networks:
      - monitor-net  

  elasticsearch:
    image: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./usr/share/elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"       
    restart: always
    networks:
      - monitor-net

  kibana:
    image: kibana    
    ports:
      - "5601:5601"  
    links:
      - elasticsearch
    networks:
      - monitor-net  

networks:
  monitor-net:
    driver: bridge