version: '2'

services:
 seleniumhub:
  image: selenium/hub
  ports:
    - "4444:4444"

 firefox:
  image: selenium/node-firefox
  depends_on:
    - seleniumhub
  ports:
    - 5900
  links:
    - seleniumhub
  environment:
    - HUB_PORT_4444_TCP_ADDR=seleniumhub
    - HUB_PORT_4444_TCP_PORT=4444
    
 chrome:
  image: selenium/node-chrome
  depends_on:
    - seleniumhub
  ports:
    - 5900
  links:
    - seleniumhub
  environment:
    - HUB_PORT_4444_TCP_ADDR=seleniumhub
    - HUB_PORT_4444_TCP_PORT=4444